# Generated by Django 5.0 on 2023-12-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('location', models.CharField(choices=[('left', 'Левый берег'), ('right', 'Правый берег')], max_length=10, verbose_name='Расположение')),
                ('specialization', models.CharField(choices=[('technical', 'Технический'), ('humanitarian', 'Гуманитарный')], max_length=20, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Вуз',
                'verbose_name_plural': 'Вузы',
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='residence',
            field=models.CharField(choices=[('left', 'Левый берег'), ('right', 'Правый берег')], default='left', max_length=10, verbose_name='Проживание'),
        ),
    ]
