# Generated by Django 5.0 on 2023-12-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_university_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='question_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер вопроса'),
        ),
    ]
